#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 49
#define LARGE_STATE_COUNT 21
#define SYMBOL_COUNT 49
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 3

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_LPAREN = 2,
  anon_sym_RPAREN = 3,
  anon_sym_fn = 4,
  anon_sym_DASH_GT = 5,
  sym_number = 6,
  anon_sym_PLUS = 7,
  anon_sym_DASH = 8,
  anon_sym_STAR = 9,
  anon_sym_SLASH = 10,
  anon_sym_mod = 11,
  anon_sym_true = 12,
  anon_sym_false = 13,
  anon_sym_if = 14,
  anon_sym_then = 15,
  anon_sym_else = 16,
  anon_sym_EQ_EQ = 17,
  anon_sym_BANG_EQ = 18,
  anon_sym_LT = 19,
  anon_sym_LT_EQ = 20,
  anon_sym_GT = 21,
  anon_sym_GT_EQ = 22,
  anon_sym_AMP_AMP = 23,
  anon_sym_PIPE_PIPE = 24,
  anon_sym_BANG = 25,
  sym_source_file = 26,
  sym__expression = 27,
  sym__simple_expression = 28,
  sym_lambda = 29,
  sym_application = 30,
  sym_parameters = 31,
  sym_add = 32,
  sym_sub = 33,
  sym_mult = 34,
  sym_div = 35,
  sym_mod = 36,
  sym_boolean = 37,
  sym_ctrl_if = 38,
  sym_eq = 39,
  sym_ne = 40,
  sym_lt = 41,
  sym_le = 42,
  sym_gt = 43,
  sym_ge = 44,
  sym_and = 45,
  sym_or = 46,
  sym_neg = 47,
  aux_sym_parameters_repeat1 = 48,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_fn] = "fn",
  [anon_sym_DASH_GT] = "->",
  [sym_number] = "number",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_mod] = "mod",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_if] = "if",
  [anon_sym_then] = "then",
  [anon_sym_else] = "else",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT] = ">",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_BANG] = "!",
  [sym_source_file] = "source_file",
  [sym__expression] = "_expression",
  [sym__simple_expression] = "_simple_expression",
  [sym_lambda] = "lambda",
  [sym_application] = "application",
  [sym_parameters] = "parameters",
  [sym_add] = "add",
  [sym_sub] = "sub",
  [sym_mult] = "mult",
  [sym_div] = "div",
  [sym_mod] = "mod",
  [sym_boolean] = "boolean",
  [sym_ctrl_if] = "ctrl_if",
  [sym_eq] = "eq",
  [sym_ne] = "ne",
  [sym_lt] = "lt",
  [sym_le] = "le",
  [sym_gt] = "gt",
  [sym_ge] = "ge",
  [sym_and] = "and",
  [sym_or] = "or",
  [sym_neg] = "neg",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [sym_number] = sym_number,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_mod] = anon_sym_mod,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_BANG] = anon_sym_BANG,
  [sym_source_file] = sym_source_file,
  [sym__expression] = sym__expression,
  [sym__simple_expression] = sym__simple_expression,
  [sym_lambda] = sym_lambda,
  [sym_application] = sym_application,
  [sym_parameters] = sym_parameters,
  [sym_add] = sym_add,
  [sym_sub] = sym_sub,
  [sym_mult] = sym_mult,
  [sym_div] = sym_div,
  [sym_mod] = sym_mod,
  [sym_boolean] = sym_boolean,
  [sym_ctrl_if] = sym_ctrl_if,
  [sym_eq] = sym_eq,
  [sym_ne] = sym_ne,
  [sym_lt] = sym_lt,
  [sym_le] = sym_le,
  [sym_gt] = sym_gt,
  [sym_ge] = sym_ge,
  [sym_and] = sym_and,
  [sym_or] = sym_or,
  [sym_neg] = sym_neg,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mod] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__simple_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_lambda] = {
    .visible = true,
    .named = true,
  },
  [sym_application] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_add] = {
    .visible = true,
    .named = true,
  },
  [sym_sub] = {
    .visible = true,
    .named = true,
  },
  [sym_mult] = {
    .visible = true,
    .named = true,
  },
  [sym_div] = {
    .visible = true,
    .named = true,
  },
  [sym_mod] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_ctrl_if] = {
    .visible = true,
    .named = true,
  },
  [sym_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_ne] = {
    .visible = true,
    .named = true,
  },
  [sym_lt] = {
    .visible = true,
    .named = true,
  },
  [sym_le] = {
    .visible = true,
    .named = true,
  },
  [sym_gt] = {
    .visible = true,
    .named = true,
  },
  [sym_ge] = {
    .visible = true,
    .named = true,
  },
  [sym_and] = {
    .visible = true,
    .named = true,
  },
  [sym_or] = {
    .visible = true,
    .named = true,
  },
  [sym_neg] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_cond = 1,
  field_else = 2,
  field_left = 3,
  field_right = 4,
  field_then = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_cond] = "cond",
  [field_else] = "else",
  [field_left] = "left",
  [field_right] = "right",
  [field_then] = "then",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_left, 0},
    {field_right, 2},
  [2] =
    {field_cond, 1},
    {field_else, 5},
    {field_then, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '!', 28,
        '&', 2,
        '(', 9,
        ')', 10,
        '*', 17,
        '+', 14,
        '-', 16,
        '/', 18,
        '<', 21,
        '=', 4,
        '>', 23,
        '|', 6,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(27);
      if (lookahead == '(') ADVANCE(9);
      if (lookahead == '-') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 2:
      if (lookahead == '&') ADVANCE(25);
      END_STATE();
    case 3:
      if (lookahead == '=') ADVANCE(20);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(19);
      END_STATE();
    case 5:
      if (lookahead == '>') ADVANCE(11);
      END_STATE();
    case 6:
      if (lookahead == '|') ADVANCE(26);
      END_STATE();
    case 7:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '!', 3,
        '&', 2,
        '(', 9,
        ')', 10,
        '*', 17,
        '+', 14,
        '-', 15,
        '/', 18,
        '<', 21,
        '=', 4,
        '>', 23,
        '|', 6,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(11);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(20);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'e') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'i') ADVANCE(3);
      if (lookahead == 'm') ADVANCE(4);
      if (lookahead == 't') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'l') ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(7);
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == 'f') ADVANCE(9);
      END_STATE();
    case 4:
      if (lookahead == 'o') ADVANCE(10);
      END_STATE();
    case 5:
      if (lookahead == 'h') ADVANCE(11);
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(15);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 12:
      if (lookahead == 'u') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 14:
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_mod);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 1},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 7},
  [22] = {.lex_state = 7},
  [23] = {.lex_state = 7},
  [24] = {.lex_state = 7},
  [25] = {.lex_state = 7},
  [26] = {.lex_state = 7},
  [27] = {.lex_state = 7},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 7},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 7},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 7},
  [34] = {.lex_state = 7},
  [35] = {.lex_state = 7},
  [36] = {.lex_state = 7},
  [37] = {.lex_state = 7},
  [38] = {.lex_state = 7},
  [39] = {.lex_state = 7},
  [40] = {.lex_state = 7},
  [41] = {.lex_state = 7},
  [42] = {.lex_state = 7},
  [43] = {.lex_state = 7},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_mod] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(48),
    [sym__expression] = STATE(42),
    [sym__simple_expression] = STATE(42),
    [sym_lambda] = STATE(42),
    [sym_application] = STATE(42),
    [sym_add] = STATE(42),
    [sym_sub] = STATE(42),
    [sym_mult] = STATE(42),
    [sym_div] = STATE(42),
    [sym_mod] = STATE(42),
    [sym_boolean] = STATE(42),
    [sym_ctrl_if] = STATE(42),
    [sym_eq] = STATE(42),
    [sym_ne] = STATE(42),
    [sym_lt] = STATE(42),
    [sym_le] = STATE(42),
    [sym_gt] = STATE(42),
    [sym_ge] = STATE(42),
    [sym_and] = STATE(42),
    [sym_or] = STATE(42),
    [sym_neg] = STATE(42),
    [sym_identifier] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [sym_number] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(15),
  },
  [2] = {
    [sym__expression] = STATE(29),
    [sym__simple_expression] = STATE(29),
    [sym_lambda] = STATE(29),
    [sym_application] = STATE(29),
    [sym_add] = STATE(29),
    [sym_sub] = STATE(29),
    [sym_mult] = STATE(29),
    [sym_div] = STATE(29),
    [sym_mod] = STATE(29),
    [sym_boolean] = STATE(29),
    [sym_ctrl_if] = STATE(29),
    [sym_eq] = STATE(29),
    [sym_ne] = STATE(29),
    [sym_lt] = STATE(29),
    [sym_le] = STATE(29),
    [sym_gt] = STATE(29),
    [sym_ge] = STATE(29),
    [sym_and] = STATE(29),
    [sym_or] = STATE(29),
    [sym_neg] = STATE(29),
    [sym_identifier] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [sym_number] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(15),
  },
  [3] = {
    [sym__expression] = STATE(36),
    [sym__simple_expression] = STATE(36),
    [sym_lambda] = STATE(36),
    [sym_application] = STATE(36),
    [sym_add] = STATE(36),
    [sym_sub] = STATE(36),
    [sym_mult] = STATE(36),
    [sym_div] = STATE(36),
    [sym_mod] = STATE(36),
    [sym_boolean] = STATE(36),
    [sym_ctrl_if] = STATE(36),
    [sym_eq] = STATE(36),
    [sym_ne] = STATE(36),
    [sym_lt] = STATE(36),
    [sym_le] = STATE(36),
    [sym_gt] = STATE(36),
    [sym_ge] = STATE(36),
    [sym_and] = STATE(36),
    [sym_or] = STATE(36),
    [sym_neg] = STATE(36),
    [sym_identifier] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [sym_number] = ACTIONS(23),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(15),
  },
  [4] = {
    [sym__expression] = STATE(40),
    [sym__simple_expression] = STATE(40),
    [sym_lambda] = STATE(40),
    [sym_application] = STATE(40),
    [sym_add] = STATE(40),
    [sym_sub] = STATE(40),
    [sym_mult] = STATE(40),
    [sym_div] = STATE(40),
    [sym_mod] = STATE(40),
    [sym_boolean] = STATE(40),
    [sym_ctrl_if] = STATE(40),
    [sym_eq] = STATE(40),
    [sym_ne] = STATE(40),
    [sym_lt] = STATE(40),
    [sym_le] = STATE(40),
    [sym_gt] = STATE(40),
    [sym_ge] = STATE(40),
    [sym_and] = STATE(40),
    [sym_or] = STATE(40),
    [sym_neg] = STATE(40),
    [sym_identifier] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [sym_number] = ACTIONS(27),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(15),
  },
  [5] = {
    [sym__expression] = STATE(24),
    [sym__simple_expression] = STATE(24),
    [sym_lambda] = STATE(24),
    [sym_application] = STATE(24),
    [sym_add] = STATE(24),
    [sym_sub] = STATE(24),
    [sym_mult] = STATE(24),
    [sym_div] = STATE(24),
    [sym_mod] = STATE(24),
    [sym_boolean] = STATE(24),
    [sym_ctrl_if] = STATE(24),
    [sym_eq] = STATE(24),
    [sym_ne] = STATE(24),
    [sym_lt] = STATE(24),
    [sym_le] = STATE(24),
    [sym_gt] = STATE(24),
    [sym_ge] = STATE(24),
    [sym_and] = STATE(24),
    [sym_or] = STATE(24),
    [sym_neg] = STATE(24),
    [sym_identifier] = ACTIONS(29),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [sym_number] = ACTIONS(31),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(15),
  },
  [6] = {
    [sym__expression] = STATE(23),
    [sym__simple_expression] = STATE(23),
    [sym_lambda] = STATE(23),
    [sym_application] = STATE(23),
    [sym_add] = STATE(23),
    [sym_sub] = STATE(23),
    [sym_mult] = STATE(23),
    [sym_div] = STATE(23),
    [sym_mod] = STATE(23),
    [sym_boolean] = STATE(23),
    [sym_ctrl_if] = STATE(23),
    [sym_eq] = STATE(23),
    [sym_ne] = STATE(23),
    [sym_lt] = STATE(23),
    [sym_le] = STATE(23),
    [sym_gt] = STATE(23),
    [sym_ge] = STATE(23),
    [sym_and] = STATE(23),
    [sym_or] = STATE(23),
    [sym_neg] = STATE(23),
    [sym_identifier] = ACTIONS(33),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [sym_number] = ACTIONS(35),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(15),
  },
  [7] = {
    [sym__expression] = STATE(25),
    [sym__simple_expression] = STATE(25),
    [sym_lambda] = STATE(25),
    [sym_application] = STATE(25),
    [sym_add] = STATE(25),
    [sym_sub] = STATE(25),
    [sym_mult] = STATE(25),
    [sym_div] = STATE(25),
    [sym_mod] = STATE(25),
    [sym_boolean] = STATE(25),
    [sym_ctrl_if] = STATE(25),
    [sym_eq] = STATE(25),
    [sym_ne] = STATE(25),
    [sym_lt] = STATE(25),
    [sym_le] = STATE(25),
    [sym_gt] = STATE(25),
    [sym_ge] = STATE(25),
    [sym_and] = STATE(25),
    [sym_or] = STATE(25),
    [sym_neg] = STATE(25),
    [sym_identifier] = ACTIONS(37),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [sym_number] = ACTIONS(39),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(15),
  },
  [8] = {
    [sym__expression] = STATE(22),
    [sym__simple_expression] = STATE(22),
    [sym_lambda] = STATE(22),
    [sym_application] = STATE(22),
    [sym_add] = STATE(22),
    [sym_sub] = STATE(22),
    [sym_mult] = STATE(22),
    [sym_div] = STATE(22),
    [sym_mod] = STATE(22),
    [sym_boolean] = STATE(22),
    [sym_ctrl_if] = STATE(22),
    [sym_eq] = STATE(22),
    [sym_ne] = STATE(22),
    [sym_lt] = STATE(22),
    [sym_le] = STATE(22),
    [sym_gt] = STATE(22),
    [sym_ge] = STATE(22),
    [sym_and] = STATE(22),
    [sym_or] = STATE(22),
    [sym_neg] = STATE(22),
    [sym_identifier] = ACTIONS(41),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [sym_number] = ACTIONS(43),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(15),
  },
  [9] = {
    [sym__expression] = STATE(26),
    [sym__simple_expression] = STATE(26),
    [sym_lambda] = STATE(26),
    [sym_application] = STATE(26),
    [sym_add] = STATE(26),
    [sym_sub] = STATE(26),
    [sym_mult] = STATE(26),
    [sym_div] = STATE(26),
    [sym_mod] = STATE(26),
    [sym_boolean] = STATE(26),
    [sym_ctrl_if] = STATE(26),
    [sym_eq] = STATE(26),
    [sym_ne] = STATE(26),
    [sym_lt] = STATE(26),
    [sym_le] = STATE(26),
    [sym_gt] = STATE(26),
    [sym_ge] = STATE(26),
    [sym_and] = STATE(26),
    [sym_or] = STATE(26),
    [sym_neg] = STATE(26),
    [sym_identifier] = ACTIONS(45),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [sym_number] = ACTIONS(47),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(15),
  },
  [10] = {
    [sym__expression] = STATE(27),
    [sym__simple_expression] = STATE(27),
    [sym_lambda] = STATE(27),
    [sym_application] = STATE(27),
    [sym_add] = STATE(27),
    [sym_sub] = STATE(27),
    [sym_mult] = STATE(27),
    [sym_div] = STATE(27),
    [sym_mod] = STATE(27),
    [sym_boolean] = STATE(27),
    [sym_ctrl_if] = STATE(27),
    [sym_eq] = STATE(27),
    [sym_ne] = STATE(27),
    [sym_lt] = STATE(27),
    [sym_le] = STATE(27),
    [sym_gt] = STATE(27),
    [sym_ge] = STATE(27),
    [sym_and] = STATE(27),
    [sym_or] = STATE(27),
    [sym_neg] = STATE(27),
    [sym_identifier] = ACTIONS(49),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [sym_number] = ACTIONS(51),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(15),
  },
  [11] = {
    [sym__expression] = STATE(28),
    [sym__simple_expression] = STATE(28),
    [sym_lambda] = STATE(28),
    [sym_application] = STATE(28),
    [sym_add] = STATE(28),
    [sym_sub] = STATE(28),
    [sym_mult] = STATE(28),
    [sym_div] = STATE(28),
    [sym_mod] = STATE(28),
    [sym_boolean] = STATE(28),
    [sym_ctrl_if] = STATE(28),
    [sym_eq] = STATE(28),
    [sym_ne] = STATE(28),
    [sym_lt] = STATE(28),
    [sym_le] = STATE(28),
    [sym_gt] = STATE(28),
    [sym_ge] = STATE(28),
    [sym_and] = STATE(28),
    [sym_or] = STATE(28),
    [sym_neg] = STATE(28),
    [sym_identifier] = ACTIONS(53),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [sym_number] = ACTIONS(55),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(15),
  },
  [12] = {
    [sym__expression] = STATE(21),
    [sym__simple_expression] = STATE(21),
    [sym_lambda] = STATE(21),
    [sym_application] = STATE(21),
    [sym_add] = STATE(21),
    [sym_sub] = STATE(21),
    [sym_mult] = STATE(21),
    [sym_div] = STATE(21),
    [sym_mod] = STATE(21),
    [sym_boolean] = STATE(21),
    [sym_ctrl_if] = STATE(21),
    [sym_eq] = STATE(21),
    [sym_ne] = STATE(21),
    [sym_lt] = STATE(21),
    [sym_le] = STATE(21),
    [sym_gt] = STATE(21),
    [sym_ge] = STATE(21),
    [sym_and] = STATE(21),
    [sym_or] = STATE(21),
    [sym_neg] = STATE(21),
    [sym_identifier] = ACTIONS(57),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [sym_number] = ACTIONS(59),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(15),
  },
  [13] = {
    [sym__expression] = STATE(30),
    [sym__simple_expression] = STATE(30),
    [sym_lambda] = STATE(30),
    [sym_application] = STATE(30),
    [sym_add] = STATE(30),
    [sym_sub] = STATE(30),
    [sym_mult] = STATE(30),
    [sym_div] = STATE(30),
    [sym_mod] = STATE(30),
    [sym_boolean] = STATE(30),
    [sym_ctrl_if] = STATE(30),
    [sym_eq] = STATE(30),
    [sym_ne] = STATE(30),
    [sym_lt] = STATE(30),
    [sym_le] = STATE(30),
    [sym_gt] = STATE(30),
    [sym_ge] = STATE(30),
    [sym_and] = STATE(30),
    [sym_or] = STATE(30),
    [sym_neg] = STATE(30),
    [sym_identifier] = ACTIONS(61),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [sym_number] = ACTIONS(63),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(15),
  },
  [14] = {
    [sym__expression] = STATE(31),
    [sym__simple_expression] = STATE(31),
    [sym_lambda] = STATE(31),
    [sym_application] = STATE(31),
    [sym_add] = STATE(31),
    [sym_sub] = STATE(31),
    [sym_mult] = STATE(31),
    [sym_div] = STATE(31),
    [sym_mod] = STATE(31),
    [sym_boolean] = STATE(31),
    [sym_ctrl_if] = STATE(31),
    [sym_eq] = STATE(31),
    [sym_ne] = STATE(31),
    [sym_lt] = STATE(31),
    [sym_le] = STATE(31),
    [sym_gt] = STATE(31),
    [sym_ge] = STATE(31),
    [sym_and] = STATE(31),
    [sym_or] = STATE(31),
    [sym_neg] = STATE(31),
    [sym_identifier] = ACTIONS(65),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [sym_number] = ACTIONS(67),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(15),
  },
  [15] = {
    [sym__expression] = STATE(32),
    [sym__simple_expression] = STATE(32),
    [sym_lambda] = STATE(32),
    [sym_application] = STATE(32),
    [sym_add] = STATE(32),
    [sym_sub] = STATE(32),
    [sym_mult] = STATE(32),
    [sym_div] = STATE(32),
    [sym_mod] = STATE(32),
    [sym_boolean] = STATE(32),
    [sym_ctrl_if] = STATE(32),
    [sym_eq] = STATE(32),
    [sym_ne] = STATE(32),
    [sym_lt] = STATE(32),
    [sym_le] = STATE(32),
    [sym_gt] = STATE(32),
    [sym_ge] = STATE(32),
    [sym_and] = STATE(32),
    [sym_or] = STATE(32),
    [sym_neg] = STATE(32),
    [sym_identifier] = ACTIONS(69),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [sym_number] = ACTIONS(71),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(15),
  },
  [16] = {
    [sym__expression] = STATE(41),
    [sym__simple_expression] = STATE(41),
    [sym_lambda] = STATE(41),
    [sym_application] = STATE(41),
    [sym_add] = STATE(41),
    [sym_sub] = STATE(41),
    [sym_mult] = STATE(41),
    [sym_div] = STATE(41),
    [sym_mod] = STATE(41),
    [sym_boolean] = STATE(41),
    [sym_ctrl_if] = STATE(41),
    [sym_eq] = STATE(41),
    [sym_ne] = STATE(41),
    [sym_lt] = STATE(41),
    [sym_le] = STATE(41),
    [sym_gt] = STATE(41),
    [sym_ge] = STATE(41),
    [sym_and] = STATE(41),
    [sym_or] = STATE(41),
    [sym_neg] = STATE(41),
    [sym_identifier] = ACTIONS(73),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [sym_number] = ACTIONS(75),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(15),
  },
  [17] = {
    [sym__expression] = STATE(34),
    [sym__simple_expression] = STATE(34),
    [sym_lambda] = STATE(34),
    [sym_application] = STATE(34),
    [sym_add] = STATE(34),
    [sym_sub] = STATE(34),
    [sym_mult] = STATE(34),
    [sym_div] = STATE(34),
    [sym_mod] = STATE(34),
    [sym_boolean] = STATE(34),
    [sym_ctrl_if] = STATE(34),
    [sym_eq] = STATE(34),
    [sym_ne] = STATE(34),
    [sym_lt] = STATE(34),
    [sym_le] = STATE(34),
    [sym_gt] = STATE(34),
    [sym_ge] = STATE(34),
    [sym_and] = STATE(34),
    [sym_or] = STATE(34),
    [sym_neg] = STATE(34),
    [sym_identifier] = ACTIONS(77),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [sym_number] = ACTIONS(79),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(15),
  },
  [18] = {
    [sym__expression] = STATE(33),
    [sym__simple_expression] = STATE(33),
    [sym_lambda] = STATE(33),
    [sym_application] = STATE(33),
    [sym_add] = STATE(33),
    [sym_sub] = STATE(33),
    [sym_mult] = STATE(33),
    [sym_div] = STATE(33),
    [sym_mod] = STATE(33),
    [sym_boolean] = STATE(33),
    [sym_ctrl_if] = STATE(33),
    [sym_eq] = STATE(33),
    [sym_ne] = STATE(33),
    [sym_lt] = STATE(33),
    [sym_le] = STATE(33),
    [sym_gt] = STATE(33),
    [sym_ge] = STATE(33),
    [sym_and] = STATE(33),
    [sym_or] = STATE(33),
    [sym_neg] = STATE(33),
    [sym_identifier] = ACTIONS(81),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [sym_number] = ACTIONS(83),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(15),
  },
  [19] = {
    [sym__expression] = STATE(35),
    [sym__simple_expression] = STATE(35),
    [sym_lambda] = STATE(35),
    [sym_application] = STATE(35),
    [sym_add] = STATE(35),
    [sym_sub] = STATE(35),
    [sym_mult] = STATE(35),
    [sym_div] = STATE(35),
    [sym_mod] = STATE(35),
    [sym_boolean] = STATE(35),
    [sym_ctrl_if] = STATE(35),
    [sym_eq] = STATE(35),
    [sym_ne] = STATE(35),
    [sym_lt] = STATE(35),
    [sym_le] = STATE(35),
    [sym_gt] = STATE(35),
    [sym_ge] = STATE(35),
    [sym_and] = STATE(35),
    [sym_or] = STATE(35),
    [sym_neg] = STATE(35),
    [sym_identifier] = ACTIONS(85),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [sym_number] = ACTIONS(87),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(15),
  },
  [20] = {
    [sym__expression] = STATE(43),
    [sym__simple_expression] = STATE(43),
    [sym_lambda] = STATE(43),
    [sym_application] = STATE(43),
    [sym_add] = STATE(43),
    [sym_sub] = STATE(43),
    [sym_mult] = STATE(43),
    [sym_div] = STATE(43),
    [sym_mod] = STATE(43),
    [sym_boolean] = STATE(43),
    [sym_ctrl_if] = STATE(43),
    [sym_eq] = STATE(43),
    [sym_ne] = STATE(43),
    [sym_lt] = STATE(43),
    [sym_le] = STATE(43),
    [sym_gt] = STATE(43),
    [sym_ge] = STATE(43),
    [sym_and] = STATE(43),
    [sym_or] = STATE(43),
    [sym_neg] = STATE(43),
    [sym_identifier] = ACTIONS(89),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [sym_number] = ACTIONS(91),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      sym_number,
    ACTIONS(99), 1,
      anon_sym_PLUS,
    ACTIONS(101), 1,
      anon_sym_DASH,
    ACTIONS(103), 1,
      anon_sym_STAR,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(107), 1,
      anon_sym_mod,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__simple_expression,
      sym_boolean,
    ACTIONS(109), 4,
      anon_sym_then,
      anon_sym_else,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(93), 8,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [49] = 7,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      sym_number,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__simple_expression,
      sym_boolean,
    ACTIONS(113), 5,
      anon_sym_mod,
      anon_sym_then,
      anon_sym_else,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(111), 12,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [88] = 10,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      sym_number,
    ACTIONS(103), 1,
      anon_sym_STAR,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(107), 1,
      anon_sym_mod,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__simple_expression,
      sym_boolean,
    ACTIONS(117), 4,
      anon_sym_then,
      anon_sym_else,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(115), 10,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [133] = 7,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      sym_number,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__simple_expression,
      sym_boolean,
    ACTIONS(121), 5,
      anon_sym_mod,
      anon_sym_then,
      anon_sym_else,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(119), 12,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [172] = 10,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      sym_number,
    ACTIONS(103), 1,
      anon_sym_STAR,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(107), 1,
      anon_sym_mod,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__simple_expression,
      sym_boolean,
    ACTIONS(125), 4,
      anon_sym_then,
      anon_sym_else,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(123), 10,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [217] = 7,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      sym_number,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__simple_expression,
      sym_boolean,
    ACTIONS(129), 5,
      anon_sym_mod,
      anon_sym_then,
      anon_sym_else,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(127), 12,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [256] = 7,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      sym_number,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__simple_expression,
      sym_boolean,
    ACTIONS(133), 5,
      anon_sym_mod,
      anon_sym_then,
      anon_sym_else,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(131), 12,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [295] = 12,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      sym_number,
    ACTIONS(99), 1,
      anon_sym_PLUS,
    ACTIONS(101), 1,
      anon_sym_DASH,
    ACTIONS(103), 1,
      anon_sym_STAR,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(107), 1,
      anon_sym_mod,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__simple_expression,
      sym_boolean,
    ACTIONS(137), 4,
      anon_sym_then,
      anon_sym_else,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(135), 8,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [344] = 12,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      sym_number,
    ACTIONS(99), 1,
      anon_sym_PLUS,
    ACTIONS(101), 1,
      anon_sym_DASH,
    ACTIONS(103), 1,
      anon_sym_STAR,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(107), 1,
      anon_sym_mod,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__simple_expression,
      sym_boolean,
    ACTIONS(141), 4,
      anon_sym_then,
      anon_sym_else,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(139), 8,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [393] = 12,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      sym_number,
    ACTIONS(99), 1,
      anon_sym_PLUS,
    ACTIONS(101), 1,
      anon_sym_DASH,
    ACTIONS(103), 1,
      anon_sym_STAR,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(107), 1,
      anon_sym_mod,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__simple_expression,
      sym_boolean,
    ACTIONS(145), 4,
      anon_sym_then,
      anon_sym_else,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(143), 8,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [442] = 12,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      sym_number,
    ACTIONS(99), 1,
      anon_sym_PLUS,
    ACTIONS(101), 1,
      anon_sym_DASH,
    ACTIONS(103), 1,
      anon_sym_STAR,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(107), 1,
      anon_sym_mod,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__simple_expression,
      sym_boolean,
    ACTIONS(149), 4,
      anon_sym_then,
      anon_sym_else,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(147), 8,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [491] = 12,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      sym_number,
    ACTIONS(99), 1,
      anon_sym_PLUS,
    ACTIONS(101), 1,
      anon_sym_DASH,
    ACTIONS(103), 1,
      anon_sym_STAR,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(107), 1,
      anon_sym_mod,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__simple_expression,
      sym_boolean,
    ACTIONS(153), 4,
      anon_sym_then,
      anon_sym_else,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(151), 8,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [540] = 19,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      sym_number,
    ACTIONS(99), 1,
      anon_sym_PLUS,
    ACTIONS(101), 1,
      anon_sym_DASH,
    ACTIONS(103), 1,
      anon_sym_STAR,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(107), 1,
      anon_sym_mod,
    ACTIONS(159), 1,
      anon_sym_EQ_EQ,
    ACTIONS(161), 1,
      anon_sym_BANG_EQ,
    ACTIONS(163), 1,
      anon_sym_LT,
    ACTIONS(165), 1,
      anon_sym_LT_EQ,
    ACTIONS(167), 1,
      anon_sym_GT,
    ACTIONS(169), 1,
      anon_sym_GT_EQ,
    ACTIONS(171), 1,
      anon_sym_AMP_AMP,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(157), 2,
      anon_sym_then,
      anon_sym_else,
    STATE(38), 2,
      sym__simple_expression,
      sym_boolean,
    ACTIONS(155), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_PIPE_PIPE,
  [603] = 18,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      sym_number,
    ACTIONS(99), 1,
      anon_sym_PLUS,
    ACTIONS(101), 1,
      anon_sym_DASH,
    ACTIONS(103), 1,
      anon_sym_STAR,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(107), 1,
      anon_sym_mod,
    ACTIONS(159), 1,
      anon_sym_EQ_EQ,
    ACTIONS(161), 1,
      anon_sym_BANG_EQ,
    ACTIONS(163), 1,
      anon_sym_LT,
    ACTIONS(165), 1,
      anon_sym_LT_EQ,
    ACTIONS(167), 1,
      anon_sym_GT,
    ACTIONS(169), 1,
      anon_sym_GT_EQ,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(175), 2,
      anon_sym_then,
      anon_sym_else,
    STATE(38), 2,
      sym__simple_expression,
      sym_boolean,
    ACTIONS(173), 4,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [664] = 20,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      sym_number,
    ACTIONS(99), 1,
      anon_sym_PLUS,
    ACTIONS(101), 1,
      anon_sym_DASH,
    ACTIONS(103), 1,
      anon_sym_STAR,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(107), 1,
      anon_sym_mod,
    ACTIONS(159), 1,
      anon_sym_EQ_EQ,
    ACTIONS(161), 1,
      anon_sym_BANG_EQ,
    ACTIONS(163), 1,
      anon_sym_LT,
    ACTIONS(165), 1,
      anon_sym_LT_EQ,
    ACTIONS(167), 1,
      anon_sym_GT,
    ACTIONS(169), 1,
      anon_sym_GT_EQ,
    ACTIONS(171), 1,
      anon_sym_AMP_AMP,
    ACTIONS(181), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(177), 2,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
    ACTIONS(179), 2,
      anon_sym_then,
      anon_sym_else,
    STATE(38), 2,
      sym__simple_expression,
      sym_boolean,
  [729] = 20,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      sym_number,
    ACTIONS(99), 1,
      anon_sym_PLUS,
    ACTIONS(101), 1,
      anon_sym_DASH,
    ACTIONS(103), 1,
      anon_sym_STAR,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(107), 1,
      anon_sym_mod,
    ACTIONS(159), 1,
      anon_sym_EQ_EQ,
    ACTIONS(161), 1,
      anon_sym_BANG_EQ,
    ACTIONS(163), 1,
      anon_sym_LT,
    ACTIONS(165), 1,
      anon_sym_LT_EQ,
    ACTIONS(167), 1,
      anon_sym_GT,
    ACTIONS(169), 1,
      anon_sym_GT_EQ,
    ACTIONS(171), 1,
      anon_sym_AMP_AMP,
    ACTIONS(181), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(183), 2,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
    ACTIONS(185), 2,
      anon_sym_then,
      anon_sym_else,
    STATE(38), 2,
      sym__simple_expression,
      sym_boolean,
  [794] = 2,
    ACTIONS(189), 8,
      sym_identifier,
      anon_sym_mod,
      anon_sym_true,
      anon_sym_false,
      anon_sym_then,
      anon_sym_else,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(187), 14,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_number,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [821] = 2,
    ACTIONS(193), 8,
      sym_identifier,
      anon_sym_mod,
      anon_sym_true,
      anon_sym_false,
      anon_sym_then,
      anon_sym_else,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(191), 14,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_number,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [848] = 2,
    ACTIONS(197), 8,
      sym_identifier,
      anon_sym_mod,
      anon_sym_true,
      anon_sym_false,
      anon_sym_then,
      anon_sym_else,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(195), 14,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_number,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [875] = 19,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      sym_number,
    ACTIONS(99), 1,
      anon_sym_PLUS,
    ACTIONS(101), 1,
      anon_sym_DASH,
    ACTIONS(103), 1,
      anon_sym_STAR,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(107), 1,
      anon_sym_mod,
    ACTIONS(159), 1,
      anon_sym_EQ_EQ,
    ACTIONS(161), 1,
      anon_sym_BANG_EQ,
    ACTIONS(163), 1,
      anon_sym_LT,
    ACTIONS(165), 1,
      anon_sym_LT_EQ,
    ACTIONS(167), 1,
      anon_sym_GT,
    ACTIONS(169), 1,
      anon_sym_GT_EQ,
    ACTIONS(171), 1,
      anon_sym_AMP_AMP,
    ACTIONS(181), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(199), 1,
      anon_sym_then,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__simple_expression,
      sym_boolean,
  [935] = 19,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      sym_number,
    ACTIONS(99), 1,
      anon_sym_PLUS,
    ACTIONS(101), 1,
      anon_sym_DASH,
    ACTIONS(103), 1,
      anon_sym_STAR,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(107), 1,
      anon_sym_mod,
    ACTIONS(159), 1,
      anon_sym_EQ_EQ,
    ACTIONS(161), 1,
      anon_sym_BANG_EQ,
    ACTIONS(163), 1,
      anon_sym_LT,
    ACTIONS(165), 1,
      anon_sym_LT_EQ,
    ACTIONS(167), 1,
      anon_sym_GT,
    ACTIONS(169), 1,
      anon_sym_GT_EQ,
    ACTIONS(171), 1,
      anon_sym_AMP_AMP,
    ACTIONS(181), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(201), 1,
      anon_sym_RPAREN,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__simple_expression,
      sym_boolean,
  [995] = 19,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      sym_number,
    ACTIONS(99), 1,
      anon_sym_PLUS,
    ACTIONS(101), 1,
      anon_sym_DASH,
    ACTIONS(103), 1,
      anon_sym_STAR,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(107), 1,
      anon_sym_mod,
    ACTIONS(159), 1,
      anon_sym_EQ_EQ,
    ACTIONS(161), 1,
      anon_sym_BANG_EQ,
    ACTIONS(163), 1,
      anon_sym_LT,
    ACTIONS(165), 1,
      anon_sym_LT_EQ,
    ACTIONS(167), 1,
      anon_sym_GT,
    ACTIONS(169), 1,
      anon_sym_GT_EQ,
    ACTIONS(171), 1,
      anon_sym_AMP_AMP,
    ACTIONS(181), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(203), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__simple_expression,
      sym_boolean,
  [1055] = 19,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      sym_number,
    ACTIONS(99), 1,
      anon_sym_PLUS,
    ACTIONS(101), 1,
      anon_sym_DASH,
    ACTIONS(103), 1,
      anon_sym_STAR,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(107), 1,
      anon_sym_mod,
    ACTIONS(159), 1,
      anon_sym_EQ_EQ,
    ACTIONS(161), 1,
      anon_sym_BANG_EQ,
    ACTIONS(163), 1,
      anon_sym_LT,
    ACTIONS(165), 1,
      anon_sym_LT_EQ,
    ACTIONS(167), 1,
      anon_sym_GT,
    ACTIONS(169), 1,
      anon_sym_GT_EQ,
    ACTIONS(171), 1,
      anon_sym_AMP_AMP,
    ACTIONS(181), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(205), 1,
      anon_sym_else,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__simple_expression,
      sym_boolean,
  [1115] = 3,
    ACTIONS(207), 1,
      sym_identifier,
    ACTIONS(209), 1,
      anon_sym_DASH_GT,
    STATE(45), 1,
      aux_sym_parameters_repeat1,
  [1125] = 3,
    ACTIONS(211), 1,
      sym_identifier,
    ACTIONS(214), 1,
      anon_sym_DASH_GT,
    STATE(45), 1,
      aux_sym_parameters_repeat1,
  [1135] = 3,
    ACTIONS(216), 1,
      sym_identifier,
    STATE(44), 1,
      aux_sym_parameters_repeat1,
    STATE(47), 1,
      sym_parameters,
  [1145] = 1,
    ACTIONS(218), 1,
      anon_sym_DASH_GT,
  [1149] = 1,
    ACTIONS(220), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(21)] = 0,
  [SMALL_STATE(22)] = 49,
  [SMALL_STATE(23)] = 88,
  [SMALL_STATE(24)] = 133,
  [SMALL_STATE(25)] = 172,
  [SMALL_STATE(26)] = 217,
  [SMALL_STATE(27)] = 256,
  [SMALL_STATE(28)] = 295,
  [SMALL_STATE(29)] = 344,
  [SMALL_STATE(30)] = 393,
  [SMALL_STATE(31)] = 442,
  [SMALL_STATE(32)] = 491,
  [SMALL_STATE(33)] = 540,
  [SMALL_STATE(34)] = 603,
  [SMALL_STATE(35)] = 664,
  [SMALL_STATE(36)] = 729,
  [SMALL_STATE(37)] = 794,
  [SMALL_STATE(38)] = 821,
  [SMALL_STATE(39)] = 848,
  [SMALL_STATE(40)] = 875,
  [SMALL_STATE(41)] = 935,
  [SMALL_STATE(42)] = 995,
  [SMALL_STATE(43)] = 1055,
  [SMALL_STATE(44)] = 1115,
  [SMALL_STATE(45)] = 1125,
  [SMALL_STATE(46)] = 1135,
  [SMALL_STATE(47)] = 1145,
  [SMALL_STATE(48)] = 1149,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ne, 3, 0, 1),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ne, 3, 0, 1),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mult, 3, 0, 1),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mult, 3, 0, 1),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add, 3, 0, 1),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_add, 3, 0, 1),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_neg, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_neg, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub, 3, 0, 1),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sub, 3, 0, 1),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_div, 3, 0, 1),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_div, 3, 0, 1),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mod, 3, 0, 1),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mod, 3, 0, 1),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eq, 3, 0, 1),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_eq, 3, 0, 1),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ge, 3, 0, 1),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ge, 3, 0, 1),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lt, 3, 0, 1),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lt, 3, 0, 1),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_le, 3, 0, 1),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_le, 3, 0, 1),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_gt, 3, 0, 1),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_gt, 3, 0, 1),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_or, 3, 0, 1),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_or, 3, 0, 1),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_and, 3, 0, 1),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_and, 3, 0, 1),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lambda, 4, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lambda, 4, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ctrl_if, 6, 0, 2),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ctrl_if, 6, 0, 2),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__simple_expression, 3, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__simple_expression, 3, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_application, 2, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_application, 2, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 1, 0, 0),
  [211] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [220] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lamgamma_parser(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
